services:
  - type: web
    name: skyhighevs
    runtime: node
    buildCommand: bash build-render.sh
    startCommand: node --enable-source-maps artifacts/api-server/dist/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: COREPACK_ENABLE_STRICT
        value: "0"
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: TOTP_SECRET
        sync: false
      - key: CTRL_API_URL
        sync: false
      - key: WORKER_API_KEY
        sync: false
